server {
    listen 80;
    server_name staging.mavss.co.in;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name staging.mavss.co.in;

    ssl_certificate /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;
    real_ip_header CF-Connecting-IP;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html; 
    }
}